"""import parse info

Revision ID: d67bcf4586ee
Revises: 656ac96a240f
Create Date: 2026-09-27 21:56:27.235853
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db


revision: str = 'd67bcf4586ee'
down_revision: Union[str, None] = '656ac96a240f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parse_info', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_jobs', schema=None) as batch_op:
        batch_op.drop_column('parse_info')

    # ### end Alembic commands ###
