import React, { useEffect, useMemo, useState } from 'react'
import axios from 'axios'
import { AnimatePresence, motion } from 'framer-motion'
import { Canvas, useFrame } from '@react-three/fiber'

const API = '/api'
const categories = ['Groceries', 'Eating out', 'Rent & utilities', 'Transport', 'Shopping', 'Health', 'Investments', 'Subscriptions', 'Education', 'Family', 'Other']
const paymentMethods = ['UPI', 'Debit card', 'Credit card', 'Cash', 'Net banking', 'Bank transfer', 'Auto-debit']
const kinds = [{ id: 'expense', label: 'Expense' }, { id: 'income', label: 'Income' }, { id: 'investment', label: 'Investment' }]
const kindDetails = { expense: { eyebrow: 'EVERYDAY SPEND', title: 'Capture an expense', hint: 'Track the little things and the big commitments.', placeholder: 'e.g. Dinner at Swiggy', accent: 'expense-mode' }, income: { eyebrow: 'MONEY IN', title: 'Record income', hint: 'Salary, freelance work, refunds, or any money received.', placeholder: 'e.g. September salary', accent: 'income-mode' }, investment: { eyebrow: 'BUILDING WEALTH', title: 'Log an investment', hint: 'Keep SIPs, stocks, mutual funds, and deposits visible.', placeholder: 'e.g. Nifty index SIP', accent: 'investment-mode' } }
const colors = ['#f7b267', '#70d6ff', '#c8b6ff', '#ff8fab', '#95d5b2', '#f6bd60', '#a8dadc']
const navItems = [{ id: 'overview', label: 'Overview', icon: '⌂' }, { id: 'transactions', label: 'Transactions', icon: '↕' }, { id: 'accounts', label: 'Accounts', icon: '▣' }, { id: 'investments', label: 'Investments', icon: '◈' }, { id: 'budgets', label: 'Budgets', icon: '◒' }, { id: 'bills', label: 'Bills', icon: '◷' }, { id: 'insights', label: 'Insights', icon: '◉' }, { id: 'goals', label: 'Goals', icon: '◎' }]

function money(value) { return new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0) }
function shortDate(value) { return value ? new Date(value).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) : 'Today' }

function Orbit() {
  const ref = React.useRef()
  useFrame((_, delta) => { if (ref.current) ref.current.rotation.y += delta * 0.28 })
  return <group ref={ref} rotation={[0.45, 0.2, 0]}><mesh><torusGeometry args={[1.35, 0.035, 16, 80]} /><meshBasicMaterial color="#f7b267" /></mesh><mesh><sphereGeometry args={[0.58, 32, 32]} /><meshStandardMaterial color="#ff8fab" emissive="#54233b" emissiveIntensity={0.7} /></mesh><mesh position={[1.35, 0, 0]}><sphereGeometry args={[0.12, 20, 20]} /><meshStandardMaterial color="#70d6ff" emissive="#123c52" emissiveIntensity={0.8} /></mesh></group>
}

function Icon({ children }) { return <span className="nav-icon">{children}</span> }

function TransactionRow({ item, onDelete, onEdit }) {
  const index = categories.indexOf(item.category)
  return <motion.div className="transaction-row" layout initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, height: 0 }}>
    <span className="category-badge" style={{ color: colors[index] || colors[6] }}>{(item.category || 'O').slice(0, 1)}</span>
    <div className="transaction-info"><strong>{item.title} {item.recurring ? <small className="recurring-tag">RECURRING</small> : null}</strong><span>{item.kind === 'income' ? 'Income' : item.kind === 'investment' ? 'Investment' : item.category || 'Other'}{item.payment_method ? ` · ${item.payment_method}` : ''}{item.merchant ? ` · ${item.merchant}` : ''}</span></div>
    <time>{shortDate(item.date)}</time><b className="transaction-amount">{money(item.amount)}</b><button className="icon-button edit-button" onClick={() => onEdit(item)} aria-label={`Edit ${item.title}`}>✎</button><button className="icon-button delete-button" onClick={() => onDelete(item.id)} aria-label={`Delete ${item.title}`}>×</button>
  </motion.div>
}

function CaptureForm({ form, setForm, onSubmit, saving, editing }) {
  const detail = kindDetails[form.kind]
  return <form onSubmit={onSubmit} className={`capture-form ${detail.accent}`}><div className="capture-hero"><span className="capture-orb">{form.kind === 'expense' ? '↘' : form.kind === 'income' ? '↗' : '◈'}</span><div><span className="section-kicker">{detail.eyebrow}</span><h3>{editing ? `Edit ${detail.title.toLowerCase()}` : detail.title}</h3><p>{detail.hint}</p></div></div><div className="kind-switch">{kinds.map((kind) => <button type="button" key={kind.id} className={form.kind === kind.id ? 'active' : ''} onClick={() => setForm({ ...form, kind: kind.id })}>{kind.label}</button>)}</div><label>What was it for? <span className="required">required</span><input autoFocus required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder={detail.placeholder} /></label><div className="form-row"><label>Amount in INR <span className="required">required</span><input type="number" min="0.01" step="1" required value={form.amount} onChange={(event) => setForm({ ...form, amount: event.target.value })} placeholder="0" /></label><label>Category<select value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label></div><div className="form-row"><label>Payment method<select value={form.payment_method} onChange={(event) => setForm({ ...form, payment_method: event.target.value })}>{paymentMethods.map((method) => <option key={method}>{method}</option>)}</select></label><label>When<input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /></label></div><div className="form-row"><label>Merchant <span className="optional">optional</span><input value={form.merchant} onChange={(event) => setForm({ ...form, merchant: event.target.value })} placeholder="e.g. Zepto, Swiggy" /></label><label className="check-label"><input type="checkbox" checked={form.recurring} onChange={(event) => setForm({ ...form, recurring: event.target.checked })} /> Recurring payment</label></div><label>Note <span className="optional">optional</span><input value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} placeholder="Add a little context" /></label><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : editing ? 'Save changes' : `Save ${form.kind}`} <span>↗</span></button></form>
}

function SpendingBars({ breakdown, maxCategory }) {
  if (!breakdown.length) return <div className="empty-chart">Your first category will bloom here.</div>
  return <div className="bars">{breakdown.slice(0, 6).map((item, index) => <div className="bar-row" key={item.category}><div className="bar-label"><span><i style={{ background: item.color }} />{item.category}</span><b>{money(item.amount)}</b></div><div className="bar-track"><motion.div initial={{ width: 0 }} animate={{ width: `${(item.amount / maxCategory) * 100}%` }} transition={{ duration: 0.7, delay: index * 0.08 }} style={{ background: item.color }} /></div></div>)}</div>
}

export default function App() {
  const [items, setItems] = useState([])
  const [activeView, setActiveView] = useState('overview')
  const [form, setForm] = useState({ title: '', amount: '', category: 'Groceries', notes: '', kind: 'expense', payment_method: 'UPI', merchant: '', date: new Date().toISOString().slice(0, 10), recurring: false })
  const [showCapture, setShowCapture] = useState(false)
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('All')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [toast, setToast] = useState('')
  const [accounts, setAccounts] = useState([])
  const [budgets, setBudgets] = useState([])
  const [goals, setGoals] = useState([])
  const [bills, setBills] = useState([])
  const [resourceModal, setResourceModal] = useState('')
  const [resourceForm, setResourceForm] = useState({ name: '', amount: '', category: 'Groceries', institution: '', due_date: '', target_amount: '', current_amount: '0', period: 'monthly' })
  const [motionEnabled, setMotionEnabled] = useState(true)
  const [editingTransaction, setEditingTransaction] = useState(null)
  const [editingResource, setEditingResource] = useState(null)

  async function fetchList() { try { setError(''); const [transactions, accountsResponse, budgetsResponse, goalsResponse, billsResponse] = await Promise.all([axios.get(`${API}/transactions`), axios.get(`${API}/accounts`), axios.get(`${API}/budgets`), axios.get(`${API}/goals`), axios.get(`${API}/bills`)]); setItems(transactions.data); setAccounts(accountsResponse.data); setBudgets(budgetsResponse.data); setGoals(goalsResponse.data); setBills(billsResponse.data) } catch { setError('The API is unavailable. Start FastAPI on port 8000 and refresh.') } finally { setLoading(false) } }
  useEffect(() => { fetchList() }, [])
  useEffect(() => { if (!toast) return undefined; const timer = setTimeout(() => setToast(''), 2600); return () => clearTimeout(timer) }, [toast])
  const emptyForm = () => ({ title: '', amount: '', category: 'Groceries', notes: '', kind: 'expense', payment_method: 'UPI', merchant: '', date: new Date().toISOString().slice(0, 10), recurring: false })
  function openCapture(kind = 'expense') { setEditingTransaction(null); setForm({ ...emptyForm(), kind }); setShowCapture(true) }
  function closeCapture() { setShowCapture(false); setEditingTransaction(null); setForm(emptyForm()) }
  useEffect(() => { if (showCapture && !editingTransaction) setForm((current) => ({ ...emptyForm(), kind: current.kind || 'expense' })) }, [showCapture, editingTransaction])

  async function addTransaction(event) {
    event.preventDefault()
    if (!form.title.trim() || !form.amount || Number(form.amount) <= 0) { setToast('Enter the required name and amount'); return }
    try { setSaving(true); setError(''); const payload = { ...form, amount: Number(form.amount), date: form.date ? `${form.date}T12:00:00` : undefined }; const response = editingTransaction ? await axios.put(`${API}/transactions/${editingTransaction.id}`, payload) : await axios.post(`${API}/transactions`, payload); setItems((current) => editingTransaction ? current.map((item) => item.id === editingTransaction.id ? response.data : item) : [response.data, ...current]); closeCapture(); setToast(editingTransaction ? 'Transaction updated' : 'Added to your ledger') } catch { setError('Could not save this transaction. Check that the API is running.') } finally { setSaving(false) }
  }
  async function removeTransaction(id) { try { await axios.delete(`${API}/transactions/${id}`); setItems((current) => current.filter((item) => item.id !== id)); setToast('Transaction removed') } catch { setError('Could not remove that transaction.') } }
  async function createResource(event) {
    event.preventDefault()
    const route = resourceModal === 'account' ? 'accounts' : resourceModal === 'budget' ? 'budgets' : resourceModal === 'goal' ? 'goals' : 'bills'
    const payload = resourceModal === 'account' ? { name: resourceForm.name, account_type: 'savings', institution: resourceForm.institution, opening_balance: Number(resourceForm.amount) || 0 } : resourceModal === 'budget' ? { name: resourceForm.name, category: resourceForm.category, amount: Number(resourceForm.amount), period: resourceForm.period } : resourceModal === 'goal' ? { name: resourceForm.name, target_amount: Number(resourceForm.target_amount), current_amount: Number(resourceForm.current_amount) || 0 } : { name: resourceForm.name, amount: Number(resourceForm.amount), due_date: resourceForm.due_date, frequency: resourceForm.period, status: 'upcoming' }
    const amountRequired = ['budget', 'bill'].includes(resourceModal)
    const goalRequired = resourceModal === 'goal'
    const billDateRequired = resourceModal === 'bill'
    if (!resourceForm.name.trim() || (amountRequired && (!resourceForm.amount || Number(resourceForm.amount) <= 0)) || (goalRequired && (!resourceForm.target_amount || Number(resourceForm.target_amount) <= 0)) || (billDateRequired && !resourceForm.due_date)) { setToast('Fill the fields marked required'); return }
    try { const response = editingResource ? await axios.put(`${API}/${route}/${editingResource.id}`, payload) : await axios.post(`${API}/${route}`, payload); const setter = resourceModal === 'account' ? setAccounts : resourceModal === 'budget' ? setBudgets : resourceModal === 'goal' ? setGoals : setBills; setter((current) => editingResource ? current.map((item) => item.id === editingResource.id ? response.data : item) : [response.data, ...current]); setResourceModal(''); setEditingResource(null); setResourceForm({ name: '', amount: '', category: 'Groceries', institution: '', due_date: '', target_amount: '', current_amount: '0', period: 'monthly' }); setToast(`${resourceModal} ${editingResource ? 'updated' : 'created'}`) } catch { setError(`Could not save this ${resourceModal}.`) }
  }
  function editTransaction(item) { setEditingTransaction(item); setForm({ title: item.title, amount: item.amount, category: item.category || 'Groceries', notes: item.notes || '', kind: item.kind || 'expense', payment_method: item.payment_method || 'UPI', merchant: item.merchant || '', date: item.date ? item.date.slice(0, 10) : new Date().toISOString().slice(0, 10), recurring: Boolean(item.recurring) }); setShowCapture(true) }
  function editResource(type, item) { setEditingResource(item); setResourceModal(type); setResourceForm({ name: item.name || '', amount: item.amount || item.opening_balance || '', category: item.category || 'Groceries', institution: item.institution || '', due_date: item.due_date || '', target_amount: item.target_amount || '', current_amount: item.current_amount || '0', period: item.period || item.frequency || 'monthly' }) }
  async function removeResource(type, id) { const route = `${API}/${type === 'account' ? 'accounts' : `${type}s`}/${id}`; try { await axios.delete(route); const setter = type === 'account' ? setAccounts : type === 'budget' ? setBudgets : type === 'goal' ? setGoals : setBills; setter((current) => current.filter((item) => item.id !== id)); setToast(`${type} removed`) } catch { setError(`Could not remove this ${type}.`) } }

  const total = useMemo(() => items.reduce((sum, item) => sum + Number(item.amount), 0), [items])
  const expenses = useMemo(() => items.filter((item) => (item.kind || 'expense') === 'expense').reduce((sum, item) => sum + Number(item.amount), 0), [items])
  const income = useMemo(() => items.filter((item) => item.kind === 'income').reduce((sum, item) => sum + Number(item.amount), 0), [items])
  const investments = useMemo(() => items.filter((item) => item.kind === 'investment').reduce((sum, item) => sum + Number(item.amount), 0), [items])
  const average = items.length ? total / items.length : 0
  const breakdown = useMemo(() => categories.map((category, index) => ({ category, amount: items.filter((item) => item.category === category).reduce((sum, item) => sum + Number(item.amount), 0), color: colors[index] })).filter((item) => item.amount > 0).sort((a, b) => b.amount - a.amount), [items])
  const maxCategory = Math.max(...breakdown.map((item) => item.amount), 1)
  const filteredItems = useMemo(() => items.filter((item) => (filter === 'All' || item.category === filter) && `${item.title} ${item.category} ${item.notes || ''}`.toLowerCase().includes(query.toLowerCase())), [items, filter, query])

  return <div className={`app-shell ${motionEnabled ? '' : 'motion-disabled'}`}><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <aside className="sidebar"><div className="brand"><span className="brand-mark">+</span><span>ledgerly</span></div><div className="sidebar-label">WORKSPACE</div><nav>{navItems.map((item) => <button key={item.id} className={`nav-item ${activeView === item.id ? 'active' : ''}`} onClick={() => setActiveView(item.id)}><Icon>{item.icon}</Icon>{item.label}{item.id === 'transactions' && items.length > 0 && <small>{items.length}</small>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item" onClick={() => setActiveView('settings')}><Icon>⚙</Icon>Settings</button><div className="profile-card"><span className="avatar">H</span><div><strong>Personal space</strong><span>Local workspace</span></div><span className="more">···</span></div></div></aside>
    <div className="main-shell"><header className="topbar"><button className="mobile-brand brand" onClick={() => setActiveView('overview')}><span className="brand-mark">+</span><span>ledgerly</span></button><div className="topbar-title">{navItems.find((item) => item.id === activeView)?.label || 'Settings'}</div><div className="topbar-actions"><button className="icon-button notification" onClick={() => setToast('You are all caught up')} aria-label="Notifications">♢<i /></button><button className="top-add" onClick={() => openCapture()}>+ <span>Add transaction</span></button></div></header>
      <main className="dashboard">
        {error && <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="error-banner">{error}</motion.div>}
        <AnimatePresence mode="wait">
          {activeView === 'overview' && <motion.div key="overview" className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><section className="intro-row"><div><p className="eyebrow">SUNDAY, SEPTEMBER 06, 2026 · INDIA</p><h1>Your money, <em>in motion.</em></h1><p className="intro-copy">Track every rupee, from UPI chai runs to long-term investments.</p></div><div className="hero-orbit"><Canvas camera={{ position: [0, 0, 4] }}><ambientLight intensity={0.7} /><pointLight position={[3, 3, 4]} color="#f7b267" /><Orbit /></Canvas></div></section><MetricCards total={expenses} income={income} investments={investments} average={average} count={items.length} /><section className="content-grid"><motion.div className="panel add-panel"><div className="panel-heading"><div><span className="section-kicker">QUICK CAPTURE</span><h2>Add a transaction</h2></div><span className="plus-icon">+</span></div><CaptureForm form={form} setForm={setForm} onSubmit={addTransaction} saving={saving} editing={false} /></motion.div><motion.div className="panel breakdown-panel"><PanelHeading kicker="WHERE IT GOES" title="Spending mix" action="This year⌄" /><SpendingBars breakdown={breakdown} maxCategory={maxCategory} /></motion.div></section><ActivityPanel items={items.slice(0, 5)} loading={loading} onDelete={removeTransaction} onEdit={editTransaction} onViewAll={() => setActiveView('transactions')} /></motion.div>}
          {activeView === 'transactions' && <motion.div key="transactions" className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><PageIntro kicker="YOUR LEDGER" title="Every dollar, accounted for." copy="Search, edit, review, and clean up your complete financial history." action={<button className="primary-button compact" onClick={() => { setEditingTransaction(null); setShowCapture(true) }}>+ Add transaction</button>} /><div className="panel transactions-panel"><div className="toolbar"><div className="search-box">⌕<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search transactions" /></div><select value={filter} onChange={(event) => setFilter(event.target.value)}><option>All</option>{categories.map((category) => <option key={category}>{category}</option>)}</select></div><div className="transaction-table-head"><span>DESCRIPTION</span><span>DATE</span><span>AMOUNT</span><span>ACTIONS</span></div>{loading ? <div className="empty-state">Loading your ledger...</div> : filteredItems.length ? <div className="transaction-list"><AnimatePresence>{filteredItems.map((item) => <TransactionRow key={item.id} item={item} onDelete={removeTransaction} onEdit={editTransaction} />)}</AnimatePresence></div> : <div className="empty-state"><span className="empty-orbit">⌕</span><h3>No transactions found</h3><p>Try another search or add a new entry.</p></div>}</div></motion.div>}
          {activeView === 'insights' && <motion.div key="insights" className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><PageIntro kicker="PATTERNS & SIGNALS" title="See the shape of your spending." copy="Small patterns become useful decisions when you can see them clearly." /><MetricCards total={expenses} income={income} investments={investments} average={average} count={items.length} /><section className="insights-grid"><div className="panel"><PanelHeading kicker="CATEGORY PULSE" title="Where your money goes" action="All time⌄" /><SpendingBars breakdown={breakdown} maxCategory={maxCategory} /></div><div className="panel insight-callout"><span className="insight-symbol">✦</span><span className="section-kicker">A LITTLE SIGNAL</span><h2>{breakdown[0] ? `${breakdown[0].category} is your biggest category.` : 'Your story starts with one entry.'}</h2><p>{breakdown[0] ? `${money(breakdown[0].amount)} has gone there so far. Keep tracking for a clearer monthly rhythm.` : 'Add a few transactions and Ledgerly will surface useful patterns here.'}</p><button className="ghost-button" onClick={() => setShowCapture(true)}>Capture something <span>↗</span></button></div></section></motion.div>}
          {activeView === 'accounts' && <ResourceView key="accounts" kicker="YOUR MONEY PLACES" title="Accounts, wallets, and cards." copy="Keep your savings accounts, cash, wallets, and investment accounts visible." items={accounts} empty="No accounts yet. Add your first bank account." type="account" onAdd={() => { setEditingResource(null); setResourceModal('account') }} onEdit={editResource} onDelete={removeResource} />}
          {activeView === 'investments' && <ResourceView key="investments" kicker="BUILDING WEALTH" title="Your investment universe." copy="Investments are tracked separately from everyday spending so your net worth stays meaningful." items={items.filter((item) => item.kind === 'investment')} empty="No investments recorded yet. Use Investment in Quick Capture." type="investment" />}
          {activeView === 'budgets' && <ResourceView key="budgets" kicker="SPEND WITH INTENTION" title="Budgets that feel alive." copy="Category budgets make your monthly limits visible before they become surprises." items={budgets} empty="No budgets created yet." type="budget" onAdd={() => { setEditingResource(null); setResourceModal('budget') }} onEdit={editResource} onDelete={removeResource} />}
          {activeView === 'bills' && <ResourceView key="bills" kicker="NEVER MISS A DUE DATE" title="Bills and recurring commitments." copy="Rent, EMIs, subscriptions, insurance, and SIPs belong here." items={bills} empty="No upcoming bills yet." type="bill" onAdd={() => { setEditingResource(null); setResourceModal('bill') }} onEdit={editResource} onDelete={removeResource} />}
          {activeView === 'goals' && <motion.div key="goals" className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><PageIntro kicker="YOUR NORTH STAR" title="Make room for what matters." copy="Goals turn good intentions into visible progress. These starter spaces are ready for you." action={<button className="primary-button compact" onClick={() => { setEditingResource(null); setResourceModal('goal') }}>+ Create goal</button>} /><section className="goals-grid">{goals.length ? goals.map((goal) => <GoalCard key={goal.id} goal={goal} title={goal.name} amount={money(goal.target_amount)} progress={Math.min(100, Math.round(goal.current_amount / goal.target_amount * 100))} color="#70d6ff" onEdit={editResource} onDelete={removeResource} />) : <><GoalCard title="Emergency fund" amount="₹2,50,000" progress={38} color="#70d6ff" /><GoalCard title="Dream trip" amount="₹1,20,000" progress={64} color="#f7b267" /></>}<button className="new-goal-card" onClick={() => { setEditingResource(null); setResourceModal('goal') }}><span>+</span><strong>Create a goal</strong><small>Give your next idea a place to grow</small></button></section></motion.div>}
          {activeView === 'settings' && <motion.div key="settings" className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><PageIntro kicker="YOUR SPACE" title="Make Ledgerly yours." copy="A few quiet controls for the way you like to work." /><div className="settings-grid"><div className="panel settings-panel"><SettingRow title="Currency" description="Used across your dashboard" value="INR · ₹" /><SettingRow title="Workspace" description="Your data stays on this device" value="Local only" /><SettingRow title="Export CSV" description="Spreadsheet backup for transactions" value={<button className="export-button" onClick={() => { window.location.href = `${API}/transactions/export.csv` }}>CSV ↓</button>} /><SettingRow title="Full backup" description="JSON backup for every finance module" value={<button className="export-button" onClick={() => { window.location.href = `${API}/backup.json` }}>JSON ↓</button>} /><SettingRow title="Motion" description="Animated transitions and surfaces" value={motionEnabled ? 'On' : 'Off'} toggle active={motionEnabled} onToggle={() => { setMotionEnabled(!motionEnabled); setToast(`Motion ${motionEnabled ? 'disabled' : 'enabled'}`) }} /></div><div className="panel appearance-panel"><span className="section-kicker">INDIA READY</span><h2>Built for rupees.</h2><p>Capture UPI, cash, cards, bank transfers, investments, recurring bills, and daily spending in one private workspace.</p><div className="theme-swatches"><i /><i /><i /><i /></div><button className="ghost-button" onClick={() => setToast('Your data stays local on this device')}>Local-first <span>✓</span></button></div></div></motion.div>}
        </AnimatePresence>
      </main>
    </div>
    <div className="mobile-nav">{navItems.map((item) => <button className={activeView === item.id ? 'active' : ''} key={item.id} onClick={() => setActiveView(item.id)}><span>{item.icon}</span>{item.label}</button>)}</div>
    <AnimatePresence>{showCapture && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => { setShowCapture(false); setEditingTransaction(null) }}><motion.div className="capture-modal" initial={{ y: 30, opacity: 0, scale: .97 }} animate={{ y: 0, opacity: 1, scale: 1 }} exit={{ y: 30, opacity: 0 }} onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">QUICK CAPTURE</span><h2>{editingTransaction ? 'Edit transaction' : 'Add a transaction'}</h2></div><button className="icon-button close-button" onClick={() => { setShowCapture(false); setEditingTransaction(null) }}>×</button></div><CaptureForm form={form} setForm={setForm} onSubmit={addTransaction} saving={saving} editing={Boolean(editingTransaction)} /></motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{resourceModal && <motion.div className="modal-backdrop" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setResourceModal('')}><motion.div className="capture-modal resource-modal" initial={{ y: 30, opacity: 0, scale: .97 }} animate={{ y: 0, opacity: 1, scale: 1 }} exit={{ y: 30, opacity: 0 }} onClick={(event) => event.stopPropagation()}><div className="panel-heading"><div><span className="section-kicker">NEW {resourceModal.toUpperCase()}</span><h2>Create {resourceModal}</h2></div><button className="icon-button close-button" onClick={() => setResourceModal('')}>×</button></div><form className="capture-form" onSubmit={createResource}><label>Name<input autoFocus value={resourceForm.name} onChange={(event) => setResourceForm({ ...resourceForm, name: event.target.value })} placeholder={resourceModal === 'bill' ? 'e.g. Electricity bill' : `e.g. ${resourceModal} name`} /></label>{resourceModal === 'account' && <label>Bank or institution<input value={resourceForm.institution} onChange={(event) => setResourceForm({ ...resourceForm, institution: event.target.value })} placeholder="e.g. HDFC Bank" /></label>}{resourceModal === 'budget' && <div className="form-row"><label>Category<select value={resourceForm.category} onChange={(event) => setResourceForm({ ...resourceForm, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Period<select value={resourceForm.period} onChange={(event) => setResourceForm({ ...resourceForm, period: event.target.value })}><option>monthly</option><option>weekly</option><option>yearly</option></select></label></div>}{resourceModal === 'goal' ? <div className="form-row"><label>Target in INR<input type="number" min="1" value={resourceForm.target_amount} onChange={(event) => setResourceForm({ ...resourceForm, target_amount: event.target.value })} /></label><label>Already saved<input type="number" min="0" value={resourceForm.current_amount} onChange={(event) => setResourceForm({ ...resourceForm, current_amount: event.target.value })} /></label></div> : <label>{resourceModal === 'account' ? 'Opening balance in INR' : 'Amount in INR'}<input type="number" min="0" value={resourceForm.amount} onChange={(event) => setResourceForm({ ...resourceForm, amount: event.target.value })} /></label>}{resourceModal === 'bill' && <div className="form-row"><label>Due date<input type="date" value={resourceForm.due_date} onChange={(event) => setResourceForm({ ...resourceForm, due_date: event.target.value })} /></label><label>Frequency<select value={resourceForm.period} onChange={(event) => setResourceForm({ ...resourceForm, period: event.target.value })}><option>monthly</option><option>weekly</option><option>yearly</option></select></label></div>}<button className="primary-button">Create {resourceModal} <span>↗</span></button></form></motion.div></motion.div>}</AnimatePresence>
    <AnimatePresence>{toast && <motion.div className="toast" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: 20 }}>{toast}</motion.div>}</AnimatePresence>
  </div>
}

function MetricCards({ total, income, investments, average, count }) { return <section className="metric-grid"><motion.div className="metric-card featured" whileHover={{ y: -4 }}><span className="metric-label">SPENDS TRACKED</span><strong>{money(total)}</strong><div className="metric-foot"><span className="trend-up">INR · ₹</span> Indian rupee workspace</div><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /><i /></div></motion.div><motion.div className="metric-card" whileHover={{ y: -4 }}><span className="metric-label">INCOME</span><strong>{money(income)}</strong><div className="metric-foot">Salary, refunds and inflow</div></motion.div><motion.div className="metric-card" whileHover={{ y: -4 }}><span className="metric-label">INVESTED</span><strong>{money(investments)}</strong><div className="metric-foot">Across {count} ledger entries · avg {money(average)}</div></motion.div></section> }
function PanelHeading({ kicker, title, action }) { return <div className="panel-heading"><div><span className="section-kicker">{kicker}</span><h2>{title}</h2></div>{action && <span className="period-pill">{action}</span>}</div> }
function PageIntro({ kicker, title, copy, action }) { return <section className="page-intro"><div><p className="eyebrow">{kicker}</p><h1>{title}</h1><p className="intro-copy">{copy}</p></div>{action}</section> }
function ActivityPanel({ items, loading, onDelete, onEdit, onViewAll }) { return <section className="panel activity-panel"><div className="panel-heading"><div><span className="section-kicker">LIVE LEDGER</span><h2>Recent activity</h2></div><button className="text-button" onClick={onViewAll}>View all ↗</button></div>{loading ? <div className="empty-state">Loading your ledger...</div> : items.length ? <div className="transaction-list"><AnimatePresence initial={false}>{items.map((item) => <TransactionRow key={item.id} item={item} onDelete={onDelete} onEdit={onEdit} />)}</AnimatePresence></div> : <div className="empty-state"><span className="empty-orbit">+</span><h3>Nothing recorded yet</h3><p>Add your first expense and watch your dashboard come alive.</p></div>}</section> }
function GoalCard({ goal, title, amount, progress, color, onEdit, onDelete }) { return <motion.div className="goal-card panel" whileHover={{ y: -5 }}><div className="goal-icon" style={{ color }}>◎</div><span className="section-kicker">SAVING TOWARD</span><h2>{title}</h2><strong>{amount}</strong><div className="goal-progress"><motion.div initial={{ width: 0 }} animate={{ width: `${progress}%` }} style={{ background: color }} /></div><div className="goal-foot"><span>{progress}% complete</span><span>Keep going</span></div>{goal && <div className="card-actions"><button onClick={() => onEdit('goal', goal)}>Edit</button><button onClick={() => onDelete('goal', goal.id)}>Delete</button></div>}</motion.div> }
function SettingRow({ title, description, value, toggle, active, onToggle }) { return <div className="setting-row"><div><strong>{title}</strong><span>{description}</span></div>{toggle ? <button className={`toggle ${active ? 'on' : ''}`} onClick={onToggle} aria-label={`Toggle ${title}`}><i /></button> : <span className="setting-value">{value}</span>}</div> }
function ResourceView({ kicker, title, copy, items, empty, type, onAdd, onEdit, onDelete }) { return <motion.div className="view" initial={{ opacity: 0, x: 12 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -12 }}><PageIntro kicker={kicker} title={title} copy={copy} action={<button className="primary-button compact" onClick={onAdd}>+ Add {type}</button>} /><div className="resource-grid">{items.length ? items.map((item) => <motion.div className="resource-card panel" key={item.id} whileHover={{ y: -4 }}><span className="resource-icon">{type === 'bill' ? '◷' : type === 'budget' ? '◒' : type === 'investment' ? '◈' : '▣'}</span><span className="section-kicker">{type.toUpperCase()}</span><h2>{item.name || item.title}</h2><strong>{money(item.amount || item.target_amount || item.opening_balance)}</strong><p>{item.institution || item.category || item.merchant || item.due_date || 'Local finance record'}</p><div className="card-actions"><button onClick={() => onEdit(type, item)}>Edit</button><button onClick={() => onDelete(type, item.id)}>Delete</button></div></motion.div>) : <div className="panel empty-resource"><span className="empty-orbit">+</span><h3>{empty}</h3><button className="ghost-button" onClick={onAdd}>Create {type} <span>↗</span></button></div>}</div></motion.div> }
